# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

State.create(:name => "location_Adygeja", :value => "Республика Адыгея")
State.create(:name => "location_Bashkirija", :value => "Республика Башкортостан")
State.create(:name => "tag_location_RespublikaBurjatija", :value => "Республика Бурятия")
State.create(:name => "location_Altajjskijj_krajj", :value => "Алтайский край")
State.create(:name => "dag", :value => "Республика Дагестан")
State.create(:name => "location_Ingushetija", :value => "Республика Ингушетия")
State.create(:name => "kbr", :value => "Кабардино-Балкарская Республика (КБР)")
State.create(:name => "location_Kalmykija", :value => "Республика Калмыкия")
State.create(:name => "kchr_reg", :value => "Карачаево-Черкесская республика (КЧР)")
State.create(:name => "location_Karelija", :value => "Республика Карелия")
State.create(:name => "tag_location_RespublikaKomi", :value => "Республика Коми")
State.create(:name => "mariel", :value => "Республика Марий Эл")
State.create(:name => "mordovia", :value => "Республика Мордовия")
State.create(:name => "location_respublika-sakha--", :value => "Республика Саха (Якутия)")
State.create(:name => "alania", :value => "Республика Северная Осетия - Алания")
State.create(:name => "location_Tatarstan", :value => "Республика Татарстан (Татарстан)")
State.create(:name => "location_Tyva/", :value => "Республика Тыва")
State.create(:name => "location_Udmurtija", :value => "Удмуртская Республика (Удмуртия)")

State.create(:name => "location_KHakasija", :value => "Республика Хакасия")
State.create(:name => "chr", :value => "Чеченская республика")
State.create(:name => "location_CHuvashija", :value => "Чувашская Республика (Чувашия)")
State.create(:name => "location_Altajjskijj_krajj", :value => "Алтайский край")
State.create(:name => "location_Krasnodarskijj_krajj", :value => "Краснодарский край")
State.create(:name => "location_Krasnojarskijj_krajj", :value => "Красноярский край")
State.create(:name => "location_Primorskijj_krajj", :value => "Приморский край")
State.create(:name => "location_Stavropolskijj_krajj", :value => "Ставропольский край")
State.create(:name => "location_KHabarovskijj_krajj", :value => "Хабаровский край")
State.create(:name => "location_Amurskaja_oblast", :value => "Амурская область")
State.create(:name => "location_Arkhangelskaja_oblast", :value => "Архангельская область")
State.create(:name => "location_Astrakhanskaja_oblast", :value => "Астраханская область")

State.create(:name => "location_Belgorodskaja_oblast", :value => "Белгородская область")
State.create(:name => "location_Brjanskaja_oblast", :value => "Брянская область")
State.create(:name => "location_Vladimirskaja_oblast", :value => "Владимирская область")
State.create(:name => "location_Volgogradskaja_oblast", :value => "Волгоградская область")
State.create(:name => "location_Voronezhskaja_oblast", :value => "Воронежская область")

State.create(:name => "location_Ivanovskaja_oblast", :value => "Ивановская область")
State.create(:name => "location_Irkutskaja_oblast", :value => "Иркутская область")
State.create(:name => "location_Kaliningradskaja_oblast", :value => "Калининградская область")
State.create(:name => "location_Kaluzhskaja_oblast", :value => "Калужская область")
State.create(:name => "location_Kamchatskijj_krajj", :value => "Камчатский край")

State.create(:name => "location_Kemerovskaja_oblast", :value => "Кемеровская область")
State.create(:name => "location_Kirovskaja_oblast", :value => "Кировская область")
State.create(:name => "location_Kostromskaja_oblast", :value => "Костромская область")
State.create(:name => "location_Kurganskaja_oblast", :value => "Курганская область")
State.create(:name => "location_Kurskaja_oblast", :value => "Курская область")

State.create(:name => "location_Leningradskaja_oblast", :value => "Ленинградская область")
State.create(:name => "location_Lipeckaja_oblast", :value => "Липецкая область")
State.create(:name => "location_Magadanskaja_oblast", :value => "Магаданская область")
State.create(:name => "location_Moskovskaja_oblast", :value => "Московская область (Подмосковье)")
State.create(:name => "location_Moskva", :value => "Москва")
State.create(:name => "location_Sankt_Peterburg", :value => "Санкт-Петербург")